FROM nvidia/cuda:12.6.3-runtime-ubuntu24.04

# Install the "docker" command
RUN apt-get update && \
  apt-get install -y nvtop curl && \
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
  chmod a+r /etc/apt/keyrings/docker.asc && \
  echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list && \
  apt-get update && \
  apt-get install --no-install-recommends docker-ce-cli && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /app

# CUDA compat - make sure this works on older kernels
# https://docs.nvidia.com/deploy/cuda-compatibility/index.html#deployment-model-for-forward-compatibility
ENV LD_LIBRARY_PATH=/usr/local/cuda/compat:$LD_LIBRARY_PATH

# Copy built binaries
COPY --chmod=755 ./benchmark /app/
COPY --chmod=755 ./kalypso-cli /app/
COPY --chmod=755 ./kalypso-attestation-prover /app/
COPY --chmod=755 ./test-connection /app/

# Copy the scripts
COPY ./*.sh /app/
RUN chmod +x *.sh

EXPOSE 3030
EXPOSE 9999

# Define default command (modify as needed)
ENTRYPOINT ["./entrypoint.sh"]
